// Generated by CoffeeScript 1.3.1
(function() {
  var empty_svg, init_svg, rect1, rect3, title;

  empty_svg = function() {
    return d3.select('div.output').append('svg');
  };

  rect1 = function() {
    var svg;
    svg = d3.select('div.output').append('svg');
    return svg.append("rect").attr("x", 150).attr("y", 100).attr("width", 60).attr("height", 300);
  };

  rect3 = function() {
    var svg;
    svg = d3.select('div.output').append('svg');
    svg.append("rect").attr("x", 200).attr("y", 300).attr("width", 40).attr("height", 50);
    svg.append("rect").attr("x", 100).attr("y", 20).attr("width", 30).attr("height", 50);
    return svg.append("rect").attr("x", 10).attr("y", 200).attr("width", 25).attr("height", 90);
  };

  slide.title("Core D3");

  slide.code_title(title = ".select()");

  slide.code(title, rect1, "var svg = d3.select(\"div.output svg\")\n\n\n");

  slide.code(title, rect1, "var svg = d3.select(\"div.output svg\")\n\n// Chain style\nsvg.select(\"rect\")\n  .attr(\"width\", 100)\n  .attr(\"height\", 100)\n  .style(\"fill\", \"steelblue\")");

  slide.code(title, rect1, "var svg = d3.select(\"div.output svg\")\n\n// Object map style\nsvg.select(\"rect\")\n  .attr({\n    width: 100,\n    height: 100\n  })\n  .style(\"fill\", \"steelblue\")");

  slide.code_title(title = ".selectAll()");

  slide.code(title, rect3, "var svg = d3.select(\"div.output svg\")\n\nsvg.select(\"rect\")\n  .attr(\"width\", 100)\n  .attr(\"height\", 100)\n  .style(\"fill\", \"steelblue\")");

  slide.code_title(title = ".data()");

  slide.code(title, rect3, "var svg = d3.select(\"div.output svg\")\n\nsvg.selectAll(\"rect\")\n  .data([227, 256, 240])\n  .attr(\"x\", 0)\n  .attr(\"width\", 100)\n  .attr(\"height\", 20)\n  .style(\"fill\", \"steelblue\")");

  slide.code_title(title = ".enter()");

  slide.code(title, rect3, "var svg = d3.select(\"div.output svg\")\n\nvar selection = svg.selectAll(\"rect\")\n  .data([127, 61, 256, 71])\n\nselection\n  .attr(\"x\", 0)\n  .attr(\"y\", function(d,i) { return i*90+50 })\n  .attr(\"width\", function(d,i) { return d; })\n  .attr(\"height\", 20)\n  .style(\"fill\", \"steelblue\")");

  slide.code(title, rect3, "var svg = d3.select(\"div.output svg\")\n\nvar selection = svg.selectAll(\"rect\")\n  .data([127, 61, 256, 71])\n\nselection\n  .attr(\"x\", 0)\n  .attr(\"y\", function(d,i) { return i*90+50 })\n  .attr(\"width\", function(d,i) { return d; })\n  .attr(\"height\", 20)\n  .style(\"fill\", \"steelblue\")\n\nselection.enter().append(\"rect\")\n  .attr(\"x\", 10) // let's just put it somewhere\n  .attr(\"y\", 10)\n  .attr(\"width\", 30)\n  .attr(\"height\", 30)\n  .style(\"fill\", \"green\")");

  slide.code(title, rect3, "var svg = d3.select(\"div.output svg\")\n\nvar selection = svg.selectAll(\"rect\")\n  .data([127, 61, 256, 71])\n\nselection\n  .attr(\"x\", 0)\n  .attr(\"y\", function(d,i) { return i*90+50 })\n  .attr(\"width\", function(d,i) { return d; })\n  .attr(\"height\", 20)\n  .style(\"fill\", \"steelblue\")\n\nselection.enter().append(\"rect\")\n  .attr(\"x\", 0)\n  .attr(\"y\", function(d,i) { return i*90+50 })\n  .attr(\"width\", function(d,i) { return d; })\n  .attr(\"height\", 20)\n  .style(\"fill\", \"steelblue\")");

  title += " // a common pattern";

  slide.code(title, empty_svg, "var svg = d3.select(\"div.output svg\")\n\nsvg.selectAll(\"rect\")\n  .data([127, 61, 256])\n  .enter().append(\"rect\")\n    .attr(\"x\", 0)\n    .attr(\"y\", function(d,i) { return i*90+50 })\n    .attr(\"width\", function(d,i) { return d; })\n    .attr(\"height\", 20)\n    .style(\"fill\", \"steelblue\")");

  slide.code_title(title = ".exit()");

  slide.code(title, rect3, "var svg = d3.select(\"div.output svg\")\n\nvar selection = svg.selectAll(\"rect\")\n  .data([127, 61])\n\nselection\n  .attr(\"x\", 0)\n  .attr(\"y\", function(d,i) { return i*90+50 })\n  .attr(\"width\", function(d,i) { return d; })\n  .attr(\"height\", 20)\n  .style(\"fill\", \"steelblue\")");

  slide.code(title, rect3, "var svg = d3.select(\"div.output svg\")\n\nvar selection = svg.selectAll(\"rect\")\n  .data([127, 61])\n\nselection\n  .attr(\"x\", 0)\n  .attr(\"y\", function(d,i) { return i*90+50 })\n  .attr(\"width\", function(d,i) { return d; })\n  .attr(\"height\", 20)\n  .style(\"fill\", \"steelblue\")\n\nselection.exit()\n  .remove()");

  slide.code_title(title = ".transition()");

  slide.code(title, rect3, "var svg = d3.select(\"div.output svg\")\n\nsvg.selectAll(\"rect\")\n  .data([127, 61, 256])\n  .attr(\"x\", 0)\n    .attr(\"y\", function(d,i) { return i*90+50 })\n    .attr(\"width\", function(d,i) { return d; })\n    .attr(\"height\", 20)\n    .style(\"fill\", \"steelblue\")");

}).call(this);
